export const GET_TRENDING_STICKERS_STARTED   = 'GET_TRENDING_STICKERS_STARTED'
export const GET_TRENDING_STICKERS_SUCCEEDED = 'GET_TRENDING_STICKERS_SUCCEEDED'
export const GET_TRENDING_STICKERS_FAILED    = 'GET_TRENDING_STICKERS_FAILED'
